### ISSUE TITLE
if statement

### ISSUE THREAD

**Issue by lpil** [lpil/elixir-jot#5]
First class like Jade, or inline Elixir like slim?

``` jade
if arriving
  div Hi
else
  div Bye
```

``` jade
if arriving do
  div Hi
else
  div Bye
```

``` slim
= if arriving do
  div Hi
- else
  div Bye
```

**Comment by jonnyarnold** [comment]
I suppose this is dependent on how you want to implement this. To me, there are two things you can do:
1. Allow the author to use all of Elixir in the template. This promotes the Slim style: "Use `-` when you want to write Elixir" is easy to explain.
2. Provide a subset of first-class constructs that look different to Elixir. If you don't make them look different, authors are going to assume they can use all Elixir constructs in the template in language, and will be disappointed if they aren't allowed.

Personally, I'd go for 2. It's more work, but it allows you to only permit the kinds of constructs you think should be in a templating system.

**Comment by lpil** [comment]
I'm going to be building EEx AST and then and then feeding it to the EEx engine, so there's nothing stopping users from using regular Elixir functions and macros.

I have to have embedded Elixir to allow people to use things like the form building macros one gets in Phoenix, etc.

First class constructs might give them a nudge to work a certain way.

**Comment by jonnyarnold** [comment]
Possibly, but I'd be worried about giving authors two ways to do something (use first-class constructs or use Elixir's constructs).

I'd do option 1 from above, given that you need to provide full Elixir access. It indicates clearly to the author when "the rules change" (when you go from Template to Elixir), and will be simpler to implement than building first-class constructs.

RE: Getting people to "do the right thing", you could lint it with dogma with template-specific rules?
