### ISSUE TITLE
case statement

### ISSUE THREAD

**Issue by lpil** [lpil/elixir-jot#6]
What should the syntax be for first class cases statements?

``` slim
case friends
  as 0
    p you have no friends
  as n when n < 10
    p you have friends
  as _
    p you have lots of friends
```

``` slim
case friends
  match 0
    p you have no friends
  match n when n < 10
    p you have friends
  match _
    p you have lots of friends
```

Happy with `case` and the style of indentation, but I'm not sure about `match` or `as`

I want to use `when` but that clashes with guards.

**Comment by jonnyarnold** [comment]
I prefer `match`; `as` doesn't make sense to me.

**Comment by lpil** [comment]
Me too. Not sure I like either that much. Other words welcome.
